INSERT INTO Sensores VALUES( 1,'DAVIS', 'Barometro');
INSERT INTO Sensores VALUES( 2,'DAVIS', 'Barlovento' );
INSERT INTO Sensores VALUES(12,'DAVIS', 'Heliografo');
INSERT INTO Sensores VALUES( 8,'DAVIS', 'Higrometro');
INSERT INTO Sensores VALUES(10,'DAVIS', 'Anemometro');
INSERT INTO Sensores VALUES(13,'DAVIS', 'Pluviografo');
INSERT INTO Sensores VALUES( 7,'NIMBUS','Pluviometro');
INSERT INTO Sensores VALUES(19,'NIMBUS','Psicrometro');
INSERT INTO Sensores VALUES(16,'NIMBUS','Termometro');
INSERT INTO Sensores VALUES( 9,'TFA',   'Barometro');
INSERT INTO Sensores VALUES( 3,'TFA',   'Barlovento');
INSERT INTO Sensores VALUES( 4,'TFA',   'Heliografo' );
INSERT INTO Sensores VALUES( 6,'TFA',   'Higrometro'  );
INSERT INTO Sensores VALUES(14,'TFA',   'Anemometro'  );
INSERT INTO Sensores VALUES(15,'TFA',   'Pluviografo'  );
INSERT INTO Sensores VALUES(11,'TFA',   'Pluviometro');
INSERT INTO Sensores VALUES(17,'GORE',  'Psicrometro' );
INSERT INTO Sensores VALUES( 5,'GORE',  'Termometro'  );
INSERT INTO Sensores VALUES(18,'GORE',  'Heliografo' );
